In [8]:
import pandas as pd
import numpy as np
filename = "Dataset"
df1 = pd.read_csv(filename+"/DrDOS_DNS.csv")
df2 = pd.read_csv(filename+"/DrDOS_LDAP.csv")
df3 = pd.read_csv(filename+"/DrDOS_MSSQL.csv")
df4 = pd.read_csv(filename+"/DrDOS_NTP.csv")
df5 = pd.read_csv(filename+"/DrDOS_NetBIOS.csv")
df6 = pd.read_csv(filename+"/DrDOS_SNMP.csv")
df7 = pd.read_csv(filename+"/DrDOS_SSDP.csv")
df8 = pd.read_csv(filename+"/DrDOS_UDP.csv")
df9 = pd.read_csv(filename+"/Syn.csv")
df10 = pd.read_csv(filename+"/UDP_LAG.csv")
dataset = [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10]
dataset = pd.concat(dataset)

In [9]:
print(dataset)

      Unnamed: 0                                 Flow ID     Source IP  \
0            425    172.16.0.5-192.168.50.1-634-60495-17    172.16.0.5   
1            430    172.16.0.5-192.168.50.1-60495-634-17  192.168.50.1   
2           1654    172.16.0.5-192.168.50.1-634-46391-17    172.16.0.5   
3           2927    172.16.0.5-192.168.50.1-634-11894-17    172.16.0.5   
4            694    172.16.0.5-192.168.50.1-634-27878-17    172.16.0.5   
...          ...                                     ...           ...   
7603       78938  172.16.0.5-192.168.50.1-43973-64923-17    172.16.0.5   
7604      101964  172.16.0.5-192.168.50.1-54238-20274-17    172.16.0.5   
7605      250040   172.16.0.5-192.168.50.1-56877-9948-17    172.16.0.5   
7606      261053  172.16.0.5-192.168.50.1-54239-55339-17    172.16.0.5   
7607       23404  172.16.0.5-192.168.50.1-38680-31160-17    172.16.0.5   

       Source Port  Destination IP   Destination Port   Protocol  \
0              634    192.168.50.1         

In [10]:
dataset.dtypes

Unnamed: 0           int64
Flow ID             object
 Source IP          object
 Source Port         int64
 Destination IP     object
                    ...   
 Idle Max          float64
 Idle Min          float64
SimillarHTTP        object
 Inbound             int64
Label               object
Length: 88, dtype: object

In [13]:
labels = np.unique(dataset['Label']).tolist()
columns = dataset.columns

In [16]:
dataset.isna().sum() > 0

Unnamed: 0         False
Flow ID            False
 Source IP         False
 Source Port       False
 Destination IP    False
                   ...  
 Idle Max          False
 Idle Min          False
SimillarHTTP       False
 Inbound           False
Label              False
Length: 88, dtype: bool

In [22]:
dataset.dtypes.values

array([dtype('int64'), dtype('O'), dtype('O'), dtype('int64'), dtype('O'),
       dtype('int64'), dtype('int64'), dtype('O'), dtype('int64'),
       dtype('int64'), dtype('int64'), dtype('float64'), dtype('float64'),
       dtype('float64'), dtype('float64'), dtype('float64'),
       dtype('float64'), dtype('float64'), dtype('float64'),
       dtype('float64'), dtype('float64'), dtype('float64'),
       dtype('float64'), dtype('float64'), dtype('float64'),
       dtype('float64'), dtype('float64'), dtype('float64'),
       dtype('float64'), dtype('float64'), dtype('float64'),
       dtype('float64'), dtype('float64'), dtype('float64'),
       dtype('float64'), dtype('float64'), dtype('float64'),
       dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'),
       dtype('int64'), dtype('int64'), dtype('float64'), dtype('float64'),
       dtype('float64'), dtype('float64'), dtype('float64'),
       dtype('float64'), dtype('float64'), dtype('int64'), dtype('int64'),
       dtype(

In [33]:
label_encoder =[]
columns = dataset.columns
types = dataset.dtypes.values
from sklearn.preprocessing import LabelEncoder

In [51]:
for i in range(len(types)):
    name = types[i]
    if name == 'O' and columns[i] !='Label':
        le = LabelEncoder()
        dataset[columns[i]] = pd.Series(le.fit_transform(dataset[columns[i]].astype(str)))
        label_encoder.append(le)
        print(columns[i])
dataset.fillna(0, inplace = True)

def getLabel(name):
    label = -1
    for i in range(len(labels)):
        if name == labels[i]:
            label = i
            break
    return label

Flow ID
 Source IP
 Destination IP
 Timestamp
SimillarHTTP


In [52]:
    Y = dataset['Label'].ravel()
    temp = []
    for i in range(len(Y)):
        temp.append(getLabel(Y[i]))
    temp = np.asarray(temp)
    Y = temp
    dataset = dataset.values

In [124]:
print(Y)
print(dataset)

[ 1  1  1 ... 10 10 10]
[[425 1357 8 ... 0 1 'DrDoS_DNS']
 [430 1190 10 ... 0 0 'DrDoS_DNS']
 [1654 1405 8 ... 0 1 'DrDoS_DNS']
 ...
 [250040 739 8 ... 0 1 'UDP-lag']
 [261053 2576 8 ... 0 1 'UDP-lag']
 [23404 423 28 ... 0 1 'UDP-lag']]


In [130]:
  X = dataset[:,0:dataset.shape[1]-1]

In [131]:
print(X)

[[425 1357 8 ... 0.0 0 1]
 [430 1190 10 ... 0.0 0 0]
 [1654 1405 8 ... 0.0 0 1]
 ...
 [250040 739 8 ... 0.0 0 1]
 [261053 2576 8 ... 0.0 0 1]
 [23404 423 28 ... 0.0 0 1]]


In [140]:
for i in X:
    for x in i:
        i[np.isinf(x)] = 0 

In [141]:
print(X)

[[425 1357 8 ... 0.0 0 1]
 [430 1190 10 ... 0.0 0 0]
 [1654 1405 8 ... 0.0 0 1]
 ...
 [250040 739 8 ... 0.0 0 1]
 [261053 2576 8 ... 0.0 0 1]
 [23404 423 28 ... 0.0 0 1]]


In [142]:
for i in X:
    for x in i:
        if np.isinf(x) == True:
            print("HI")

In [143]:
print(X)

[[425 1357 8 ... 0.0 0 1]
 [430 1190 10 ... 0.0 0 0]
 [1654 1405 8 ... 0.0 0 1]
 ...
 [250040 739 8 ... 0.0 0 1]
 [261053 2576 8 ... 0.0 0 1]
 [23404 423 28 ... 0.0 0 1]]


In [148]:
import pickle
import os

In [149]:
if os.path.exists('model/nb.txt'):
        with open('model/nb.txt', 'rb') as file:
            nb = pickle.load(file)
        file.close()        
else:
        nb = GaussianNB() 
        nb.fit(X_train, y_train)
        with open('model/nb.txt', 'wb') as file:
            pickle.dump(nb, file)
        file.close()      
print(nb)

UnpicklingError: pickle data was truncated

In [156]:
from sklearn
db = open('model/knn.txt','rb')
dbfile = pickle.load(db)
for lines in dbfile:
    print(lines)

ModuleNotFoundError: No module named 'sklearn.neighbors._dist_metrics'

In [158]:
pip install numpy==1.19.2

     ---------------------------------------- 0.0/7.3 MB ? eta -:--:--
     --------- ------------------------------ 1.8/7.3 MB 37.9 MB/s eta 0:00:01
     -------------------- ------------------- 3.7/7.3 MB 39.2 MB/s eta 0:00:01
     ---------------------- ----------------- 4.2/7.3 MB 44.4 MB/s eta 0:00:01
     ---------------------- ----------------- 4.2/7.3 MB 44.4 MB/s eta 0:00:01
     ---------------------- ----------------- 4.2/7.3 MB 44.4 MB/s eta 0:00:01
     ---------------------- ----------------- 4.2/7.3 MB 44.4 MB/s eta 0:00:01
     ---------------------- ----------------- 4.2/7.3 MB 44.4 MB/s eta 0:00:01
     ---------------------- ----------------- 4.2/7.3 MB 44.4 MB/s eta 0:00:01
     ----------------------------------- ---- 6.4/7.3 MB 15.1 MB/s eta 0:00:01
     ---------------------------------------- 7.3/7.3 MB 16.1 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel

  error: subprocess-exited-with-error
  
  Preparing metadata (pyproject.toml) did not run successfully.
  exit code: 1
  
  [93 lines of output]
  Running from numpy source directory.
  setup.py:470: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
    run_build = parse_setuppy_commands()
  performance hint: _common.pyx:275:19: Exception check after calling 'random_func' will always require the GIL to be acquired. Declare 'random_func' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
  performance hint: _common.pyx:299:19: Exception check after calling 'random_func' will always require the GIL to be acquired. Declare 'random_func' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
  performance hint: _common.pyx:322:50: Exception check after calling 'random_func' will always require the GIL to be acquired. 

In [159]:
python

NameError: name 'python' is not defined

Note: you may need to restart the kernel to use updated packages.



Usage:   
  C:\Users\markp\anaconda3\python.exe -m pip <command> [options]

no such option: --V
